name: Daily Contributions

on:
  schedule:
    - cron: '0 0 * * 1-5' 
  workflow_dispatch: 

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make daily contribution
        run: |
          echo "Making daily contribution"
          echo "$(date)" >> README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Daily contribution"
          add: "README.md"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
